CREATE TABLE pie_exif_data (
       ped_mob_id BIGINT NOT NULL,
       ped_artist VARCHAR(255),
       ped_copyright VARCHAR(255),
       ped_software VARCHAR(64),
       ped_date_time VARCHAR(32),
       ped_lens_model VARCHAR(32),       
       ped_make VARCHAR(16),
       ped_model VARCHAR(16),
       ped_exposure_time VARCHAR(16),       
       ped_sub_sec_time INTEGER,
       ped_x_dim INTEGER,
       ped_y_dim INTEGER,       
       ped_iso INTEGER,
       ped_gamma INTEGER,
       ped_white_point INTEGER,       
       ped_orientation SMALLINT,
       ped_focal_len SMALLINT,
       ped_fnumber SMALLINT,
       ped_exposure_bias SMALLINT,
       ped_white_balance SMALLINT,
       ped_exposure_prog SMALLINT,
       ped_metering_mode SMALLINT,
       ped_flash SMALLINT,
       ped_exposure_mode SMALLINT,
       ped_color_space SMALLINT,
       PRIMARY KEY(ped_mob_id));
